export const newsConstants = {
    LOAD_SUCCESS: 'NEWS_LOADED_SUCCESS',
    LOAD_ALL_SUCCESS: 'ALL_NEWS_LOADED_SUCCESS',
    LOAD_FAILURE: 'NEWS_LOADED_FAILURE',

    STORE_SUCCESS: 'NEWS_CLICkED_SAVE_SUCCESS'
};